import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
import { randomUUID, randomBytes } from 'node:crypto';
import { createRound, publicRound } from '../game/engine.js';
import { createDailyDeck, dailySeed, localDate } from '../game/daily.js';
import { mulberry32 } from '../game/rng.js';

const keys = ['roundNumber','hiddenState','difficulty','signalStrength','volatility','trend','riskIndicator','safeProbability','pushProbability','yoloProbability','safeGain','pushGain','yoloGain','safeLoss','pushLoss','yoloLoss','safeRoll','pushRoll','yoloRoll'];
const columns = ['round_number','hidden_state','difficulty','signal_strength','volatility','trend','risk_indicator','safe_probability','push_probability','yolo_probability','safe_gain','push_gain','yolo_gain','safe_loss','push_loss','yolo_loss','safe_roll','push_roll','yolo_roll'];
const camel = (row) => row && Object.fromEntries(Object.entries(row).map(([key, value]) => [key.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase()), value]));
const toRound = (row) => { const c = camel(row); return c && { ...c, trend: JSON.parse(c.trend) }; };
export function createStore(filename = path.resolve('data/stack.db')) {
  fs.mkdirSync(path.dirname(filename), { recursive: true }); const db = new Database(filename); db.pragma('foreign_keys = ON'); db.exec(fs.readFileSync(new URL('./schema.sql', import.meta.url), 'utf8'));
  const insertRound = db.prepare(`INSERT INTO rounds (id,run_id,${columns.join(',')}) VALUES (@id,@runId,${columns.map(c => '@' + c.replace(/_([a-z])/g, (_,l)=>l.toUpperCase())).join(',')})`);
  function saveRound(runId, round) { const data = { id: randomUUID(), runId }; keys.forEach((key) => { data[key] = key === 'trend' ? JSON.stringify(round[key]) : round[key]; }); insertRound.run(data); }
  function getRun(id) { return camel(db.prepare('SELECT * FROM runs WHERE id=?').get(id)); }
  function getRound(runId, unresolved = false) { const sql = `SELECT * FROM rounds WHERE run_id=? ${unresolved ? 'AND choice IS NULL' : ''} ORDER BY round_number ${unresolved ? 'ASC' : 'DESC'} LIMIT 1`; return toRound(db.prepare(sql).get(runId)); }
  function getCurrentRound(run) { return toRound(db.prepare('SELECT * FROM rounds WHERE run_id=? AND round_number=?').get(run.id, run.currentRoundNumber)); }
  function publicRun(run) { if (!run) return null; const result = { id: run.id, mode: run.mode, status: run.status, currentScore: run.currentScore, highestScore: run.highestScore, streak: run.streak, roundsCompleted: run.roundsCompleted }; if (run.mode === 'daily') result.dailyDate = run.dailyDate; if (run.status === 'banked' || run.status === 'busted') Object.assign(result, { finalScore: run.finalScore, maxStreak: run.maxStreak, biggestGain: run.biggestGain, riskProfile: run.riskProfile, bankRound: run.bankRound, endedAt: run.endedAt }); return result; }
  const create = db.transaction((mode) => { const id = randomUUID(), now = new Date().toISOString(), seed = mode === 'daily' ? 0 : requireRandomSeed(); const date = mode === 'daily' ? localDate() : null; db.prepare('INSERT INTO runs (id,mode,status,started_at,daily_date,daily_seed,rng_seed,current_score,highest_score) VALUES (?,?,?,?,?,?,?,?,?)').run(id, mode, 'active', now, date, date && dailySeed(date), seed, 100, 100); if (mode === 'daily') createDailyDeck(date).forEach((round) => saveRound(id, round)); else saveRound(id, createRound(1, null, mulberry32(seed))); return { run: publicRun(getRun(id)), round: publicRound(getRound(id, true)) }; });
  function requireRandomSeed() { return cryptoSeed(); }
  function cryptoSeed() { return randomBytes(4).readUInt32LE(0); }
  const resolve = db.transaction((id, choice) => { const run = getRun(id); if (!run) return { error: 'NOT_FOUND' }; if (run.status !== 'active') return { error: 'INVALID_STATE' }; const round = getCurrentRound(run); if (!round || round.choice) return { error: 'INVALID_STATE' }; const key = choice.toLowerCase(), roll = round[`${key}Roll`]; const success = roll < round[`${key}Probability`]; const scoreAfter = success ? Math.min(9999999, Math.round(run.currentScore * (1 + round[`${key}Gain`]))) : Math.max(0, Math.round(run.currentScore * (1 - round[`${key}Loss`]))); const bust = scoreAfter <= 20; const now = new Date().toISOString(); db.prepare('UPDATE rounds SET choice=?, success=?, score_before=?, score_after=?, resolved_at=? WHERE run_id=? AND round_number=?').run(choice, Number(success), run.currentScore, scoreAfter, now, id, round.roundNumber); const status = bust ? 'busted' : success ? 'awaiting_decision' : 'active'; const streak = success ? run.streak + 1 : 0; db.prepare('UPDATE runs SET status=?, current_score=?, final_score=?, highest_score=?, rounds_completed=rounds_completed+1, streak=?, max_streak=MAX(max_streak,?), biggest_gain=MAX(biggest_gain,?), ended_at=?, updated_at=? WHERE id=?').run(status, scoreAfter, bust ? scoreAfter : null, Math.max(run.highestScore, scoreAfter), streak, streak, Math.max(0, scoreAfter - run.currentScore), bust ? now : null, now, id); const updated = getRun(id); if (bust) { const counts = choiceCounts(id); db.prepare('UPDATE runs SET risk_profile=? WHERE id=?').run(profile(updated, counts), id); } return { run: publicRun(getRun(id)), result: { choice, success, scoreBefore: run.currentScore, scoreAfter, isBust: bust, message: success ? 'SIGNAL LOCKED' : bust ? 'SYSTEM FAILURE' : 'SYSTEM HIT' } }; });
  function choiceCounts(id) { const rows = db.prepare('SELECT choice, COUNT(*) as count FROM rounds WHERE run_id=? AND choice IS NOT NULL GROUP BY choice').all(id); return Object.fromEntries(rows.map((r) => [r.choice, r.count])); }
  function profile(run, counts) { const total = (counts.SAFE || 0) + (counts.PUSH || 0) + (counts.YOLO || 0) || 1, safe = (counts.SAFE || 0) / total, yolo = (counts.YOLO || 0) / total, push = (counts.PUSH || 0) / total, banked = run.status === 'banked'; if (safe >= .65 && banked && run.roundsCompleted <= 5) return 'Risk Analyst'; if (safe >= .65 && !banked) return 'Cautious Operator'; if (yolo >= .45 && banked) return 'Calculated Menace'; if (yolo >= .45 && !banked) return 'Variance Enjoyer'; if (banked && run.roundsCompleted >= 10 && yolo < .45) return 'Stack Architect'; if (push >= .5) return 'Signal Chaser'; return 'Adaptive Operator'; }
  const continueRun = db.transaction((id) => { const run = getRun(id); if (!run) return { error: 'NOT_FOUND' }; if (run.status !== 'active' && run.status !== 'awaiting_decision') return { error: 'INVALID_STATE' }; const current = getCurrentRound(run); if (!current || !current.choice) return { error: 'INVALID_STATE' }; if (run.currentRoundNumber >= 60 && run.mode === 'daily') return { error: 'INVALID_STATE' }; if (run.mode === 'random') saveRound(id, createRound(run.currentRoundNumber + 1, current.hiddenState, mulberry32((run.rngSeed + run.currentRoundNumber * 0x9e3779b9) >>> 0))); db.prepare("UPDATE runs SET status='active', current_round_number=current_round_number+1, updated_at=? WHERE id=?").run(new Date().toISOString(), id); const updated = getRun(id); return { run: publicRun(updated), round: publicRound(getCurrentRound(updated)) }; });
  const bank = db.transaction((id) => { const run = getRun(id); if (!run) return { error: 'NOT_FOUND' }; if (run.status !== 'awaiting_decision') return { error: 'INVALID_STATE' }; const now = new Date().toISOString(); db.prepare("UPDATE runs SET status='banked', final_score=current_score, bank_round=rounds_completed, ended_at=?, updated_at=? WHERE id=?").run(now, now, id); const updated = getRun(id); db.prepare('UPDATE runs SET risk_profile=? WHERE id=?').run(profile(updated, choiceCounts(id)), id); return { run: publicRun(getRun(id)) }; });
  function read(id) { const run = getRun(id); if (!run) return null; const response = { run: publicRun(run) }; const round = getCurrentRound(run); if (round && !round.choice && run.status === 'active') response.round = publicRound(round); return response; }
  function stats() { const overall = db.prepare("SELECT COUNT(*) totalRuns, COALESCE(SUM(status='banked'),0) totalBankedRuns, COALESCE(SUM(status='busted'),0) totalBusts, COALESCE(MAX(highest_score),0) bestScore, COALESCE(ROUND(AVG(final_score)),0) averageFinalScore, COALESCE(MAX(max_streak),0) longestStreak, COALESCE(ROUND(AVG(CASE WHEN status IN ('banked','busted') THEN rounds_completed END),1),0) averageRoundsSurvived FROM runs").get(); const choices = choiceCountsAll(); return { ...camel(overall), choiceCounts: { SAFE: choices.SAFE || 0, PUSH: choices.PUSH || 0, YOLO: choices.YOLO || 0 } }; }
  function choiceCountsAll() { return Object.fromEntries(db.prepare('SELECT choice, COUNT(*) count FROM rounds WHERE choice IS NOT NULL GROUP BY choice').all().map((r) => [r.choice, r.count])); }
  return { db, create, resolve, continueRun, bank, read, stats, close: () => db.close() };
}
